apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-service-account
  namespace: fluidos
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admin-cluster-role
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-cluster-rolebinding
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin-cluster-role
subjects:
  - kind: ServiceAccount
    name: helm-service-account
    namespace: fluidos
