apiVersion: advertisement.fluidos.eu/v1alpha1
kind: PeeringCandidate
metadata:
  creationTimestamp: "2024-09-27T09:14:31Z"
  generation: 1
  name: peeringcandidate-fluidos.eu-k8slice-mio-esempio4
  namespace: fluidos
  resourceVersion: "5244"
  uid: 16c7643d-c982-4184-a168-49fcd2b658b8
spec:
  available: true
  flavor:
    metadata:
      name: fluidos.eu-k8slice-mio-esempio4
      namespace: fluidos
    spec:
      availability: true
      flavorType:
        typeData:
          characteristics:
            architecture: amd64
            cpu: 19940574197n
            gpu:
              cores: "0"
              memory: "0"
              model: ""
            memory: 7623252Ki
            pods: "110"
            storage: "0"
          policies:
            partitionability:
              cpuMin: "0"
              cpuStep: "1"
              gpuMin: "0"
              gpuStep: "0"
              memoryMin: "0"
              memoryStep: 100Mi
              podsMin: "0"
              podsStep: "0"
          properties:
            networkAuthorizations:
              mandatoryCommunications:
                - name: "AuthorizationMandatory_1"
                  source:
                    isHotCluster: false
                    resourceSelector:
                      typeIdentifier: PodNamespaceSelector
                      selector:
                        pod:
                          app: "resource-monitor"
                        namespace:
                          name: "monitoring"
                  destination:
                    resourceSelector:
                      isHotCluster: true
                      typeIdentifier: PodNamespaceSelector
                      selector:
                        pod:
                          "*" : "*"
                        namespace:
                          "*" : "*"
                  destinationPort: "43"
                  protocolType: "ALL"
              deniedCommunications:
                - name: "AuthorizationDeny_1"
                  source:
                    resourceSelector:
                      isHotCluster: true
                      typeIdentifier: PodNamespaceSelector
                      selector:
                        pod:
                          "*" : "*"
                        namespace:
                          "*" : "*"
                  destination:
                    resourceSelector:
                      isHotCluster: false
                      typeIdentifier: CIDRSelector
                      selector: "0.0.0.0/20"
                  destinationPort: "*"
                  protocolType: "ALL"
                - name: "AuthorizationDeny_2"
                  source:
                    resourceSelector:
                      isHotCluster: true
                      typeIdentifier: PodNamespaceSelector
                      selector:
                        pod:
                          "*" : "*"
                        namespace:
                          "*" : "*"
                  destination:
                    resourceSelector:
                      isHotCluster: false
                      typeIdentifier: PodNamespaceSelector
                      selector:
                        pod:
                          "*" : "*"
                        namespace:
                          name: "handle-payments"
                  destinationPort: "*"
                  protocolType: "SCTP"
                - name: "AuthorizationDeny_3"
                  source:
                    resourceSelector:
                      isHotCluster: true
                      typeIdentifier: PodNamespaceSelector
                      selector:
                        pod:
                          "*" : "*"
                        namespace:
                          "*" : "*"
                  destination:
                    resourceSelector:
                      isHotCluster: false
                      typeIdentifier: PodNamespaceSelector
                      selector:
                        pod:
                          "*" : "*"
                        namespace:
                          name: "handle-payments"
                  destinationPort: "0-79"
                  protocolType: "TCP"
                - name: "AuthorizationDeny_4"
                  source:
                    resourceSelector:
                      isHotCluster: true
                      typeIdentifier: PodNamespaceSelector
                      selector:
                        pod:
                          "*" : "*"
                        namespace:
                          "*" : "*"
                  destination:
                    resourceSelector:
                      isHotCluster: false
                      typeIdentifier: PodNamespaceSelector
                      selector:
                        pod:
                          "*" : "*"
                        namespace:
                          name: "handle-payments"
                  destinationPort: "0-79"
                  protocolType: "UDP"
                - name: "AuthorizationDeny_5"
                  source:
                    resourceSelector:
                      isHotCluster: true
                      typeIdentifier: PodNamespaceSelector
                      selector:
                        pod:
                          "*" : "*"
                        namespace:
                          "*" : "*"
                  destination:
                    resourceSelector:
                      isHotCluster: false
                      typeIdentifier: PodNamespaceSelector
                      selector:
                        pod:
                          "*" : "*"
                        namespace:
                          name: "handle-payments"
                  destinationPort: "86-100"
                  protocolType: "UDP"
        typeIdentifier: K8Slice
      location:
        additionalNotes: None
        city: Turin
        country: Italy
        latitude: "10"
        longitude: "58"
      networkPropertyType: networkProperty
      owner:
        domain: fluidos.eu
        ip: 172.18.0.6:30001
        nodeID: z2h7lyofqs
      price:
        amount: ""
        currency: ""
        period: ""
      providerID: z2h7lyofqs
    status:
      creationTime: ""
      expirationTime: ""
      lastUpdateTime: ""
  solverID: solver-sample
status:
  creationTime: "2024-09-27T09:14:31Z"
  lastUpdateTime: ""
