apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: peeringcandidates-binding
subjects:
- kind: ServiceAccount
  name: "custom-controller"
  namespace: fluidos  
roleRef:
  kind: ClusterRole
  name: "peeringcandidates-cluster-role"
  apiGroup: rbac.authorization.k8s.io
