apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: configmap-cluster-role-binding
  namespace: fluidos
subjects:
  - kind: ServiceAccount
    name: custom-controller
    namespace: fluidos
roleRef:
  kind: ClusterRole
  name: configmap-cluster-role
  apiGroup: rbac.authorization.k8s.io
