apiVersion: apps/v1
kind: Deployment
metadata:
  name: help-desk
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: help-desk
  template:
    metadata:
      labels:
        app: help-desk
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c", "while true; do echo hello; sleep 10; done"]
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "32Mi"
            cpu: "20m"