apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "costum-controller"
  namespace: fluidos
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list","watch"]