apiVersion: nodecore.fluidos.eu/v1alpha1
kind: Flavor
metadata:
  creationTimestamp: "2024-09-28T16:00:22Z"
  generation: 1
  name: fluidos.eu-k8slice-demo-2
  namespace: fluidos
  ownerReferences:
    - apiVersion: nodecore.fluidos.eu/v1alpha1
      kind: Node
      name: fluidos-provider-1-worker
      uid: 7318c786-26a3-44ef-ac4e-0dc34a6c7ec4
  resourceVersion: "10629"
  uid: 5b15836d-5085-498c-a22a-4b5bf6f31143
spec:
  availability: true
  flavorType:
    typeData:
      characteristics:
        architecture: amd64
        cpu: 15888001127n
        gpu:
          cores: "0"
          memory: "0"
          model: ""
        memory: 7147688Ki
        pods: "110"
        storage: "0"
      properties:
        networkAuthorizations:
          mandatoryCommunications:
            - name: "AuthorizationMandatory_1"
              source:
                isHotCluster: false
                resourceSelector:
                  typeIdentifier: PodNamespaceSelector
                  selector:
                    pod:
                      app: "resource-monitor"
                    namespace:
                      name: "monitoring"
              destination:
                resourceSelector:
                  isHotCluster: true
                  typeIdentifier: PodNamespaceSelector
                  selector:
                    pod:
                      "*": "*"
                    namespace:
                      "*": "*"
              destinationPort: "43"
              protocolType: "ALL"
          deniedCommunications:
            - name: "AuthorizationDeny_1"
              source:
                resourceSelector:
                  isHotCluster: true
                  typeIdentifier: PodNamespaceSelector
                  selector:
                    pod:
                      "*": "*"
                    namespace:
                      "*": "*"
              destination:
                resourceSelector:
                  isHotCluster: false
                  typeIdentifier: CIDRSelector
                  selector: "10.0.0.0/16"
              destinationPort: "*"
              protocolType: "ALL"
            - name: "AuthorizationDeny_2"
              source:
                resourceSelector:
                  isHotCluster: true
                  typeIdentifier: PodNamespaceSelector
                  selector:
                    pod:
                      "*": "*"
                    namespace:
                      "*": "*"
              destination:
                resourceSelector:
                  isHotCluster: false
                  typeIdentifier: PodNamespaceSelector
                  selector:
                    pod:
                      "*": "*"
                    namespace:
                      name: "handle-payments"
              destinationPort: "*"
              protocolType: "SCTP"
            - name: "AuthorizationDeny_3"
              source:
                resourceSelector:
                  isHotCluster: true
                  typeIdentifier: PodNamespaceSelector
                  selector:
                    pod:
                      "*": "*"
                    namespace:
                      "*": "*"
              destination:
                resourceSelector:
                  isHotCluster: false
                  typeIdentifier: PodNamespaceSelector
                  selector:
                    pod:
                      "*": "*"
                    namespace:
                      name: "handle-payments"
              destinationPort: "82-120"
              protocolType: "TCP"
      policies:
        partitionability:
          cpuMin: "0"
          cpuStep: "1"
          gpuMin: "0"
          gpuStep: "0"
          memoryMin: "0"
          memoryStep: 100Mi
          podsMin: "0"
          podsStep: "0"
    typeIdentifier: K8Slice
  location:
    additionalNotes: None
    city: Turin
    country: Italy
    latitude: "10"
    longitude: "58"
  networkPropertyType: networkProperty
  owner:
    domain: fluidos.eu
    ip: "172.18.0.6:30001"
    nodeID: "esamauglzj"
  price:
    amount: ""
    currency: ""
    period: ""
  providerID: "esamauglzj"
