apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: privateintent1
  namespace: default
spec:
  policyTypes:
  - Ingress
  podSelector:
    matchLabels:
      app: product-catalogue
  ingress:
  - from:
    - podSelector: {}
    ports:
    - port: 80
      protocol: TCP
