apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prova-rome-a2d9d20
  namespace: prova-rome-a2d9d2
spec:
  policyTypes:
  - Ingress
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: default
      podSelector: {}
    ports:
    - port: 80
      protocol: TCP