apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: requestintent4monitoring6
  namespace: monitoring
spec:
  policyTypes:
  - Egress
  podSelector: {}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: fluidos
      podSelector:
        matchLabels:
          app: order-placement
