apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: requestintent4fluidos5
  namespace: fluidos
spec:
  policyTypes:
  - Ingress
  podSelector:
    matchLabels:
      app: order-placement
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
      podSelector: {}
