apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: requestintent2
  namespace: fluidos
spec:
  policyTypes:
  - Egress
  podSelector:
    matchLabels:
      app: bank_payment
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: default
