apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: RequestIntent_4
  namespace: fluidos
spec:
  policyTypes:
  - Ingress
  podSelector:
    matchLabels:
      app: order_placement
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
      podSelector: {}
