apiVersion: nodecore.fluidos.eu/v1alpha1
kind: Flavor
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"nodecore.fluidos.eu/v1alpha1","kind":"Flavor","metadata":{"annotations":{},"creationTimestamp":"2024-08-28T12:07:34Z","generation":1,"name":"fluidos.eu-k8slice-959c63e4db855ff2a100f6662ec558b9","namespace":"fluidos","ownerReferences":[{"apiVersion":"nodecore.fluidos.eu/v1alpha1","kind":"Node","name":"fluidos-consumer-1-worker2","uid":"bad59ebd-c431-46b8-8f99-e535c4b72fe9"}],"resourceVersion":"1950","uid":"31396de5-4c1d-48f7-91fc-1bf3b8e37ed4"},"spec":{"availability":true,"flavorType":{"typeData":{"characteristics":{"architecture":"amd64","cpu":"19940574197n","gpu":{"cores":"0","memory":"0","model":""},"memory":"7623252Ki","pods":"110","storage":"0"},"policies":{"partitionability":{"cpuMin":"0","cpuStep":"1","gpuMin":"0","gpuStep":"0","memoryMin":"0","memoryStep":"100Mi","podsMin":"0","podsStep":"0"}},"properties":{}},"typeIdentifier":"K8Slice"},"location":{"additionalNotes":"None","city":"Turin","country":"Italy","latitude":"10","longitude":"58"},"networkPropertyType":"networkProperty","owner":{"domain":"fluidos.eu","ip":"172.18.0.7:30000","nodeID":"qcezneafhv"},"price":{"amount":"","currency":"","period":""},"providerID":"qcezneafhv"}}
  creationTimestamp: "2024-08-28T12:07:34Z"
  generation: 1
  name: fluidos.eu-k8slice-959c63e4db855ff2a100f6662ec558b9
  namespace: fluidos
  ownerReferences:
  - apiVersion: nodecore.fluidos.eu/v1alpha1
    kind: Node
    name: fluidos-consumer-1-worker2
    uid: bad59ebd-c431-46b8-8f99-e535c4b72fe9
  resourceVersion: "6544"
  uid: 31396de5-4c1d-48f7-91fc-1bf3b8e37ed4
spec:
  availability: true
  flavorType:
    typeData:
      characteristics:
        architecture: amd64
        cpu: 19940574197n
        gpu:
          cores: "0"
          memory: "0"
          model: ""
        memory: 7623252Ki
        pods: "110"
        storage: "0"
      policies:
        partitionability:
          cpuMin: "0"
          cpuStep: "1"
          gpuMin: "0"
          gpuStep: "0"
          memoryMin: "0"
          memoryStep: 100Mi
          podsMin: "0"
          podsStep: "0"
      properties: {}
    typeIdentifier: K8Slice
  location:
    additionalNotes: None
    city: Turin
    country: Italy
    latitude: "10"
    longitude: "58"
  networkPropertyType: networkProperty
  owner:
    domain: fluidos.eu
    ip: 172.18.0.7:30000
    nodeID: qcezneafhv
  price:
    amount: ""
    currency: ""
    period: ""
  providerID: qcezneafhv
