{{- $resManagerConfig := (merge (dict "name" "local-resource-manager" "module" "local-resource-manager") .) -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fluidos.prefixedName" $resManagerConfig }}
  labels:
    {{- include "fluidos.labels" $resManagerConfig | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "fluidos.prefixedName" $resManagerConfig }}
  labels:
    {{- include "fluidos.labels" $resManagerConfig | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "fluidos.prefixedName" $resManagerConfig }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "fluidos.prefixedName" $resManagerConfig }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fluidos.prefixedName" $resManagerConfig }}
  labels:
    {{- include "fluidos.labels" $resManagerConfig | nindent 4 }}
{{ .Files.Get (include "fluidos.cluster-role-filename" (dict "prefix" ( include "fluidos.prefixedName" $resManagerConfig )))}}

