{{- $rearControllerConfig := (merge (dict "name" "rear-controller" "module" "rear-controller") .) -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fluidos.prefixedName" $rearControllerConfig }}
  labels:
    {{- include "fluidos.labels" $rearControllerConfig | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "fluidos.prefixedName" $rearControllerConfig }}
  labels:
    {{- include "fluidos.labels" $rearControllerConfig | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "fluidos.prefixedName" $rearControllerConfig }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "fluidos.prefixedName" $rearControllerConfig }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fluidos.prefixedName" $rearControllerConfig }}
  labels:
    {{- include "fluidos.labels" $rearControllerConfig | nindent 4 }}
{{ .Files.Get (include "fluidos.cluster-role-filename" (dict "prefix" ( include "fluidos.prefixedName" $rearControllerConfig )))}}

