apiVersion: v1
kind: ConfigMap
metadata:
  name: configure-liqo-script
  labels:
    app: liqo
data:
  configure-liqo.sh: |
    #!/bin/sh
    kubectl patch deployment liqo-controller-manager -n liqo --type='json' -p='[
      {
        "op": "add",
        "path": "/spec/template/spec/containers/0/args/-",
        "value": "--enable-resource-enforcement"
      },
      {
        "op": "add",
        "path": "/spec/template/spec/containers/0/args/-",
        "value": "--resource-plugin-address=node-rear-controller-grpc.fluidos:2710"
      }
    ]'