apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-3
  namespace: handle-payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-3
  template:
    metadata:
      labels:
        app: bank-3
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80        
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "32Mi"
            cpu: "20m"
