{{- $rearManagerConfig := (merge (dict "name" "rear-manager" "module" "rear-manager") .) -}}

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "fluidos.prefixedName" $rearManagerConfig }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "fluidos.prefixedName" $rearManagerConfig }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "fluidos.prefixedName" $rearManagerConfig }}
      namespace: {{ .Release.Namespace }}
      path: /validate-nodecore-fluidos-eu-v1alpha1-solver
  failurePolicy: Fail
  name: validate.solver.nodecore.fluidos.eu
  rules:
  - apiGroups:
    - nodecore.fluidos.eu
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - solvers
  sideEffects: None
# - admissionReviewVersions:
#   - v1
#   - v1beta1
#   clientConfig:
#     service:
#       name: {{ include "fluidos.prefixedName" $rearManagerConfig }}
#       namespace: {{ .Release.Namespace }}
#       path: /validate/peeringcandidate
#   failurePolicy: Ignore
#   name: pc.validate.fluidos.eu
#   rules:
#   - apiGroups:
#     - advertisement.node.fluidos.io
#     apiVersions:
#     - v1alpha1
#     operations:
#     - CREATE
#     - UPDATE
#     - DELETE
#     resources:
#     - peeringcandidates
#   sideEffects: None