//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.14 at 09:34:48 AM CET 
//


package eu.fluidos.jaxb;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ActionParameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActionParameters"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="keyExchange" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}KeyExchangeParameter" minOccurs="0"/&gt;
 *         &lt;element name="technologyParameter" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}TechnologySpecificParameters" maxOccurs="unbounded"/&gt;
 *         &lt;element name="additionalNetworkConfigurationParameters" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}AdditionalNetworkConfigurationParameters" minOccurs="0"/&gt;
 *         &lt;element name="authenticationParameters" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}AuthenticationParameters" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActionParameters", propOrder = {
    "keyExchange",
    "technologyParameter",
    "additionalNetworkConfigurationParameters",
    "authenticationParameters"
})
public class ActionParameters {

    protected KeyExchangeParameter keyExchange;
    @XmlElement(required = true)
    protected List<TechnologySpecificParameters> technologyParameter;
    protected AdditionalNetworkConfigurationParameters additionalNetworkConfigurationParameters;
    protected AuthenticationParameters authenticationParameters;

    /**
     * Gets the value of the keyExchange property.
     * 
     * @return
     *     possible object is
     *     {@link KeyExchangeParameter }
     *     
     */
    public KeyExchangeParameter getKeyExchange() {
        return keyExchange;
    }

    /**
     * Sets the value of the keyExchange property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyExchangeParameter }
     *     
     */
    public void setKeyExchange(KeyExchangeParameter value) {
        this.keyExchange = value;
    }

    /**
     * Gets the value of the technologyParameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the technologyParameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTechnologyParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TechnologySpecificParameters }
     * 
     * 
     */
    public List<TechnologySpecificParameters> getTechnologyParameter() {
        if (technologyParameter == null) {
            technologyParameter = new ArrayList<TechnologySpecificParameters>();
        }
        return this.technologyParameter;
    }

    /**
     * Gets the value of the additionalNetworkConfigurationParameters property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalNetworkConfigurationParameters }
     *     
     */
    public AdditionalNetworkConfigurationParameters getAdditionalNetworkConfigurationParameters() {
        return additionalNetworkConfigurationParameters;
    }

    /**
     * Sets the value of the additionalNetworkConfigurationParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalNetworkConfigurationParameters }
     *     
     */
    public void setAdditionalNetworkConfigurationParameters(AdditionalNetworkConfigurationParameters value) {
        this.additionalNetworkConfigurationParameters = value;
    }

    /**
     * Gets the value of the authenticationParameters property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticationParameters }
     *     
     */
    public AuthenticationParameters getAuthenticationParameters() {
        return authenticationParameters;
    }

    /**
     * Sets the value of the authenticationParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticationParameters }
     *     
     */
    public void setAuthenticationParameters(AuthenticationParameters value) {
        this.authenticationParameters = value;
    }

}
