//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.14 at 09:34:48 AM CET 
//


package eu.fluidos.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdditionalParameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdditionalParameters"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}ConfigurationCondition"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="encoderLayers" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="decoderLayers" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="encoderNeurons" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="decoderNeurons" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="codeNeurons" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="lossFunction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="epsilon" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="delta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdditionalParameters", propOrder = {
    "encoderLayers",
    "decoderLayers",
    "encoderNeurons",
    "decoderNeurons",
    "codeNeurons",
    "lossFunction",
    "epsilon",
    "delta"
})
public class AdditionalParameters
    extends ConfigurationCondition
{

    protected String encoderLayers;
    protected String decoderLayers;
    protected String encoderNeurons;
    protected String decoderNeurons;
    protected String codeNeurons;
    protected String lossFunction;
    protected String epsilon;
    protected String delta;

    /**
     * Gets the value of the encoderLayers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncoderLayers() {
        return encoderLayers;
    }

    /**
     * Sets the value of the encoderLayers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncoderLayers(String value) {
        this.encoderLayers = value;
    }

    /**
     * Gets the value of the decoderLayers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecoderLayers() {
        return decoderLayers;
    }

    /**
     * Sets the value of the decoderLayers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecoderLayers(String value) {
        this.decoderLayers = value;
    }

    /**
     * Gets the value of the encoderNeurons property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncoderNeurons() {
        return encoderNeurons;
    }

    /**
     * Sets the value of the encoderNeurons property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncoderNeurons(String value) {
        this.encoderNeurons = value;
    }

    /**
     * Gets the value of the decoderNeurons property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecoderNeurons() {
        return decoderNeurons;
    }

    /**
     * Sets the value of the decoderNeurons property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecoderNeurons(String value) {
        this.decoderNeurons = value;
    }

    /**
     * Gets the value of the codeNeurons property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeNeurons() {
        return codeNeurons;
    }

    /**
     * Sets the value of the codeNeurons property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeNeurons(String value) {
        this.codeNeurons = value;
    }

    /**
     * Gets the value of the lossFunction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLossFunction() {
        return lossFunction;
    }

    /**
     * Sets the value of the lossFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLossFunction(String value) {
        this.lossFunction = value;
    }

    /**
     * Gets the value of the epsilon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpsilon() {
        return epsilon;
    }

    /**
     * Sets the value of the epsilon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpsilon(String value) {
        this.epsilon = value;
    }

    /**
     * Gets the value of the delta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelta() {
        return delta;
    }

    /**
     * Sets the value of the delta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelta(String value) {
        this.delta = value;
    }

}
