//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.14 at 09:34:48 AM CET 
//


package eu.fluidos.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CheckAction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CheckAction"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}ConfigurationAction"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CheckActionType" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}CheckActionType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CheckAction", propOrder = {
    "checkActionType"
})
public class CheckAction
    extends ConfigurationAction
{

    @XmlElement(name = "CheckActionType", required = true)
    protected CheckActionType checkActionType;

    /**
     * Gets the value of the checkActionType property.
     * 
     * @return
     *     possible object is
     *     {@link CheckActionType }
     *     
     */
    public CheckActionType getCheckActionType() {
        return checkActionType;
    }

    /**
     * Sets the value of the checkActionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CheckActionType }
     *     
     */
    public void setCheckActionType(CheckActionType value) {
        this.checkActionType = value;
    }

}
