//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.14 at 09:34:48 AM CET 
//


package eu.fluidos.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConfigurationCondition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConfigurationCondition"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="isCNF" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConfigurationCondition", propOrder = {
    "isCNF"
})
@XmlSeeAlso({
    PolicyDependencyCondition.class,
    FiveGSecuritySliceCondition.class,
    PurposeCondition.class,
    DataAgreggationConfigurationConditions.class,
    MonitoringConfigurationConditions.class,
    NetworkSlicingCondition.class,
    NetworkSlicingConditionParameters.class,
    Point.class,
    ParametersFirewallConfigurationCondition.class,
    RuleParameters.class,
    FilterFLConfigurationCondition.class,
    AggregatorParameters.class,
    LocalConnectionParameters.class,
    LearningParameters.class,
    ObfuscationInfo.class,
    Parameters.class,
    LearningModelInfo.class,
    ModelParameters.class,
    AdditionalParameters.class,
    IntegrationFabricParameters.class,
    Topics.class,
    Topic.class,
    QoSCondition.class,
    AntiMalwareCondition.class,
    LoggingCondition.class,
    DataProtectionCondition.class,
    FilteringConfigurationCondition.class,
    KubernetesNetworkFilteringCondition.class
})
public class ConfigurationCondition {

    protected boolean isCNF;

    /**
     * Gets the value of the isCNF property.
     * 
     */
    public boolean isIsCNF() {
        return isCNF;
    }

    /**
     * Sets the value of the isCNF property.
     * 
     */
    public void setIsCNF(boolean value) {
        this.isCNF = value;
    }

}
