//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.14 at 09:34:48 AM CET 
//


package eu.fluidos.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataProtectionCapability complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataProtectionCapability"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}Capability"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="supportsDataAuthenticationAndIntegrity" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="supportsDigitalSignature" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="supportsEncryption" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="supportsKeyExchange" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataProtectionCapability", propOrder = {
    "supportsDataAuthenticationAndIntegrity",
    "supportsDigitalSignature",
    "supportsEncryption",
    "supportsKeyExchange"
})
@XmlSeeAlso({
    EncryptionCapability.class
})
public class DataProtectionCapability
    extends Capability
{

    protected boolean supportsDataAuthenticationAndIntegrity;
    protected boolean supportsDigitalSignature;
    protected boolean supportsEncryption;
    protected boolean supportsKeyExchange;

    /**
     * Gets the value of the supportsDataAuthenticationAndIntegrity property.
     * 
     */
    public boolean isSupportsDataAuthenticationAndIntegrity() {
        return supportsDataAuthenticationAndIntegrity;
    }

    /**
     * Sets the value of the supportsDataAuthenticationAndIntegrity property.
     * 
     */
    public void setSupportsDataAuthenticationAndIntegrity(boolean value) {
        this.supportsDataAuthenticationAndIntegrity = value;
    }

    /**
     * Gets the value of the supportsDigitalSignature property.
     * 
     */
    public boolean isSupportsDigitalSignature() {
        return supportsDigitalSignature;
    }

    /**
     * Sets the value of the supportsDigitalSignature property.
     * 
     */
    public void setSupportsDigitalSignature(boolean value) {
        this.supportsDigitalSignature = value;
    }

    /**
     * Gets the value of the supportsEncryption property.
     * 
     */
    public boolean isSupportsEncryption() {
        return supportsEncryption;
    }

    /**
     * Sets the value of the supportsEncryption property.
     * 
     */
    public void setSupportsEncryption(boolean value) {
        this.supportsEncryption = value;
    }

    /**
     * Gets the value of the supportsKeyExchange property.
     * 
     */
    public boolean isSupportsKeyExchange() {
        return supportsKeyExchange;
    }

    /**
     * Sets the value of the supportsKeyExchange property.
     * 
     */
    public void setSupportsKeyExchange(boolean value) {
        this.supportsKeyExchange = value;
    }

}
