//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.14 at 09:34:48 AM CET 
//


package eu.fluidos.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FederatedLearningRuleAction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FederatedLearningRuleAction"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}ConfigurationAction"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="federationLearnigActionType" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}FederationLearnigActionType" minOccurs="0"/&gt;
 *         &lt;element name="aggregatorParameters" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}FLConfigurationCondition" minOccurs="0"/&gt;
 *         &lt;element name="localConnectionParameters" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}FLConfigurationCondition" minOccurs="0"/&gt;
 *         &lt;element name="integrationFabricParameters" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}FLConfigurationCondition" minOccurs="0"/&gt;
 *         &lt;element name="learningModelInfo" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}FLConfigurationCondition" minOccurs="0"/&gt;
 *         &lt;element name="learningParameters" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}FLConfigurationCondition" minOccurs="0"/&gt;
 *         &lt;element name="obfuscationInfo" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}FLConfigurationCondition" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FederatedLearningRuleAction", propOrder = {
    "federationLearnigActionType",
    "aggregatorParameters",
    "localConnectionParameters",
    "integrationFabricParameters",
    "learningModelInfo",
    "learningParameters",
    "obfuscationInfo"
})
public class FederatedLearningRuleAction
    extends ConfigurationAction
{

    @XmlSchemaType(name = "string")
    protected FederationLearnigActionType federationLearnigActionType;
    protected FLConfigurationCondition aggregatorParameters;
    protected FLConfigurationCondition localConnectionParameters;
    protected FLConfigurationCondition integrationFabricParameters;
    protected FLConfigurationCondition learningModelInfo;
    protected FLConfigurationCondition learningParameters;
    protected FLConfigurationCondition obfuscationInfo;

    /**
     * Gets the value of the federationLearnigActionType property.
     * 
     * @return
     *     possible object is
     *     {@link FederationLearnigActionType }
     *     
     */
    public FederationLearnigActionType getFederationLearnigActionType() {
        return federationLearnigActionType;
    }

    /**
     * Sets the value of the federationLearnigActionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FederationLearnigActionType }
     *     
     */
    public void setFederationLearnigActionType(FederationLearnigActionType value) {
        this.federationLearnigActionType = value;
    }

    /**
     * Gets the value of the aggregatorParameters property.
     * 
     * @return
     *     possible object is
     *     {@link FLConfigurationCondition }
     *     
     */
    public FLConfigurationCondition getAggregatorParameters() {
        return aggregatorParameters;
    }

    /**
     * Sets the value of the aggregatorParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link FLConfigurationCondition }
     *     
     */
    public void setAggregatorParameters(FLConfigurationCondition value) {
        this.aggregatorParameters = value;
    }

    /**
     * Gets the value of the localConnectionParameters property.
     * 
     * @return
     *     possible object is
     *     {@link FLConfigurationCondition }
     *     
     */
    public FLConfigurationCondition getLocalConnectionParameters() {
        return localConnectionParameters;
    }

    /**
     * Sets the value of the localConnectionParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link FLConfigurationCondition }
     *     
     */
    public void setLocalConnectionParameters(FLConfigurationCondition value) {
        this.localConnectionParameters = value;
    }

    /**
     * Gets the value of the integrationFabricParameters property.
     * 
     * @return
     *     possible object is
     *     {@link FLConfigurationCondition }
     *     
     */
    public FLConfigurationCondition getIntegrationFabricParameters() {
        return integrationFabricParameters;
    }

    /**
     * Sets the value of the integrationFabricParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link FLConfigurationCondition }
     *     
     */
    public void setIntegrationFabricParameters(FLConfigurationCondition value) {
        this.integrationFabricParameters = value;
    }

    /**
     * Gets the value of the learningModelInfo property.
     * 
     * @return
     *     possible object is
     *     {@link FLConfigurationCondition }
     *     
     */
    public FLConfigurationCondition getLearningModelInfo() {
        return learningModelInfo;
    }

    /**
     * Sets the value of the learningModelInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link FLConfigurationCondition }
     *     
     */
    public void setLearningModelInfo(FLConfigurationCondition value) {
        this.learningModelInfo = value;
    }

    /**
     * Gets the value of the learningParameters property.
     * 
     * @return
     *     possible object is
     *     {@link FLConfigurationCondition }
     *     
     */
    public FLConfigurationCondition getLearningParameters() {
        return learningParameters;
    }

    /**
     * Sets the value of the learningParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link FLConfigurationCondition }
     *     
     */
    public void setLearningParameters(FLConfigurationCondition value) {
        this.learningParameters = value;
    }

    /**
     * Gets the value of the obfuscationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link FLConfigurationCondition }
     *     
     */
    public FLConfigurationCondition getObfuscationInfo() {
        return obfuscationInfo;
    }

    /**
     * Sets the value of the obfuscationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link FLConfigurationCondition }
     *     
     */
    public void setObfuscationInfo(FLConfigurationCondition value) {
        this.obfuscationInfo = value;
    }

}
