//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.14 at 09:34:48 AM CET 
//


package eu.fluidos.jaxb;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FilterFLConfigurationCondition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FilterFLConfigurationCondition"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}ConfigurationCondition"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="instanceThreshold" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="aggregatorParameters" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}AggregatorParameters" minOccurs="0"/&gt;
 *         &lt;element name="localConnectionParameters" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}LocalConnectionParameters" minOccurs="0"/&gt;
 *         &lt;element name="integrationFabricParameters" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}IntegrationFabricParameters" minOccurs="0"/&gt;
 *         &lt;element name="learningModelInfo" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}LearningModelInfo" minOccurs="0"/&gt;
 *         &lt;element name="learningParameters" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}LearningParameters" minOccurs="0"/&gt;
 *         &lt;element name="obfuscationInfo" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}ObfuscationInfo" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FilterFLConfigurationCondition", propOrder = {
    "instanceThreshold",
    "aggregatorParameters",
    "localConnectionParameters",
    "integrationFabricParameters",
    "learningModelInfo",
    "learningParameters",
    "obfuscationInfo"
})
@XmlSeeAlso({
    FLConfigurationCondition.class
})
public class FilterFLConfigurationCondition
    extends ConfigurationCondition
{

    protected BigInteger instanceThreshold;
    protected AggregatorParameters aggregatorParameters;
    protected LocalConnectionParameters localConnectionParameters;
    protected IntegrationFabricParameters integrationFabricParameters;
    protected LearningModelInfo learningModelInfo;
    protected LearningParameters learningParameters;
    protected ObfuscationInfo obfuscationInfo;

    /**
     * Gets the value of the instanceThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInstanceThreshold() {
        return instanceThreshold;
    }

    /**
     * Sets the value of the instanceThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInstanceThreshold(BigInteger value) {
        this.instanceThreshold = value;
    }

    /**
     * Gets the value of the aggregatorParameters property.
     * 
     * @return
     *     possible object is
     *     {@link AggregatorParameters }
     *     
     */
    public AggregatorParameters getAggregatorParameters() {
        return aggregatorParameters;
    }

    /**
     * Sets the value of the aggregatorParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link AggregatorParameters }
     *     
     */
    public void setAggregatorParameters(AggregatorParameters value) {
        this.aggregatorParameters = value;
    }

    /**
     * Gets the value of the localConnectionParameters property.
     * 
     * @return
     *     possible object is
     *     {@link LocalConnectionParameters }
     *     
     */
    public LocalConnectionParameters getLocalConnectionParameters() {
        return localConnectionParameters;
    }

    /**
     * Sets the value of the localConnectionParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalConnectionParameters }
     *     
     */
    public void setLocalConnectionParameters(LocalConnectionParameters value) {
        this.localConnectionParameters = value;
    }

    /**
     * Gets the value of the integrationFabricParameters property.
     * 
     * @return
     *     possible object is
     *     {@link IntegrationFabricParameters }
     *     
     */
    public IntegrationFabricParameters getIntegrationFabricParameters() {
        return integrationFabricParameters;
    }

    /**
     * Sets the value of the integrationFabricParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntegrationFabricParameters }
     *     
     */
    public void setIntegrationFabricParameters(IntegrationFabricParameters value) {
        this.integrationFabricParameters = value;
    }

    /**
     * Gets the value of the learningModelInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LearningModelInfo }
     *     
     */
    public LearningModelInfo getLearningModelInfo() {
        return learningModelInfo;
    }

    /**
     * Sets the value of the learningModelInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LearningModelInfo }
     *     
     */
    public void setLearningModelInfo(LearningModelInfo value) {
        this.learningModelInfo = value;
    }

    /**
     * Gets the value of the learningParameters property.
     * 
     * @return
     *     possible object is
     *     {@link LearningParameters }
     *     
     */
    public LearningParameters getLearningParameters() {
        return learningParameters;
    }

    /**
     * Sets the value of the learningParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link LearningParameters }
     *     
     */
    public void setLearningParameters(LearningParameters value) {
        this.learningParameters = value;
    }

    /**
     * Gets the value of the obfuscationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ObfuscationInfo }
     *     
     */
    public ObfuscationInfo getObfuscationInfo() {
        return obfuscationInfo;
    }

    /**
     * Sets the value of the obfuscationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObfuscationInfo }
     *     
     */
    public void setObfuscationInfo(ObfuscationInfo value) {
        this.obfuscationInfo = value;
    }

}
