//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.14 at 09:34:48 AM CET 
//


package eu.fluidos.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FilteringConfigurationCondition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FilteringConfigurationCondition"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}ConfigurationCondition"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="packetFilterCondition" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}PacketFilterCondition" minOccurs="0"/&gt;
 *         &lt;element name="ICMPCondition" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}ICMPCondition" minOccurs="0"/&gt;
 *         &lt;element name="statefulCondition" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}StatefulCondition" minOccurs="0"/&gt;
 *         &lt;element name="timeCondition" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}TimeCondition" minOccurs="0"/&gt;
 *         &lt;element name="applicationLayerCondition" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}ApplicationLayerCondition" minOccurs="0"/&gt;
 *         &lt;element name="aggregatorParameters" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}AggregatorParameters" minOccurs="0"/&gt;
 *         &lt;element name="localConnectionParameters" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}LocalConnectionParameters" minOccurs="0"/&gt;
 *         &lt;element name="qosCondition" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}QoSCondition" minOccurs="0"/&gt;
 *         &lt;element name="networkSlicingConditionParameters" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}NetworkSlicingConditionParameters" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FilteringConfigurationCondition", propOrder = {
    "packetFilterCondition",
    "icmpCondition",
    "statefulCondition",
    "timeCondition",
    "applicationLayerCondition",
    "aggregatorParameters",
    "localConnectionParameters",
    "qosCondition",
    "networkSlicingConditionParameters"
})
@XmlSeeAlso({
    PrivacyConfigurationCondition.class,
    DataAggregationConfigurationCondition.class,
    AnonymityConfigurationCondition.class,
    MonitoringConfigurationCondition.class,
    TrafficDivertConfigurationCondition.class,
    AuthorizationCondition.class,
    AuthenticationCondition.class
})
public class FilteringConfigurationCondition
    extends ConfigurationCondition
{

    protected PacketFilterCondition packetFilterCondition;
    @XmlElement(name = "ICMPCondition")
    protected ICMPCondition icmpCondition;
    protected StatefulCondition statefulCondition;
    protected TimeCondition timeCondition;
    protected ApplicationLayerCondition applicationLayerCondition;
    protected AggregatorParameters aggregatorParameters;
    protected LocalConnectionParameters localConnectionParameters;
    protected QoSCondition qosCondition;
    protected NetworkSlicingConditionParameters networkSlicingConditionParameters;

    /**
     * Gets the value of the packetFilterCondition property.
     * 
     * @return
     *     possible object is
     *     {@link PacketFilterCondition }
     *     
     */
    public PacketFilterCondition getPacketFilterCondition() {
        return packetFilterCondition;
    }

    /**
     * Sets the value of the packetFilterCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link PacketFilterCondition }
     *     
     */
    public void setPacketFilterCondition(PacketFilterCondition value) {
        this.packetFilterCondition = value;
    }

    /**
     * Gets the value of the icmpCondition property.
     * 
     * @return
     *     possible object is
     *     {@link ICMPCondition }
     *     
     */
    public ICMPCondition getICMPCondition() {
        return icmpCondition;
    }

    /**
     * Sets the value of the icmpCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link ICMPCondition }
     *     
     */
    public void setICMPCondition(ICMPCondition value) {
        this.icmpCondition = value;
    }

    /**
     * Gets the value of the statefulCondition property.
     * 
     * @return
     *     possible object is
     *     {@link StatefulCondition }
     *     
     */
    public StatefulCondition getStatefulCondition() {
        return statefulCondition;
    }

    /**
     * Sets the value of the statefulCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatefulCondition }
     *     
     */
    public void setStatefulCondition(StatefulCondition value) {
        this.statefulCondition = value;
    }

    /**
     * Gets the value of the timeCondition property.
     * 
     * @return
     *     possible object is
     *     {@link TimeCondition }
     *     
     */
    public TimeCondition getTimeCondition() {
        return timeCondition;
    }

    /**
     * Sets the value of the timeCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeCondition }
     *     
     */
    public void setTimeCondition(TimeCondition value) {
        this.timeCondition = value;
    }

    /**
     * Gets the value of the applicationLayerCondition property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationLayerCondition }
     *     
     */
    public ApplicationLayerCondition getApplicationLayerCondition() {
        return applicationLayerCondition;
    }

    /**
     * Sets the value of the applicationLayerCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationLayerCondition }
     *     
     */
    public void setApplicationLayerCondition(ApplicationLayerCondition value) {
        this.applicationLayerCondition = value;
    }

    /**
     * Gets the value of the aggregatorParameters property.
     * 
     * @return
     *     possible object is
     *     {@link AggregatorParameters }
     *     
     */
    public AggregatorParameters getAggregatorParameters() {
        return aggregatorParameters;
    }

    /**
     * Sets the value of the aggregatorParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link AggregatorParameters }
     *     
     */
    public void setAggregatorParameters(AggregatorParameters value) {
        this.aggregatorParameters = value;
    }

    /**
     * Gets the value of the localConnectionParameters property.
     * 
     * @return
     *     possible object is
     *     {@link LocalConnectionParameters }
     *     
     */
    public LocalConnectionParameters getLocalConnectionParameters() {
        return localConnectionParameters;
    }

    /**
     * Sets the value of the localConnectionParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalConnectionParameters }
     *     
     */
    public void setLocalConnectionParameters(LocalConnectionParameters value) {
        this.localConnectionParameters = value;
    }

    /**
     * Gets the value of the qosCondition property.
     * 
     * @return
     *     possible object is
     *     {@link QoSCondition }
     *     
     */
    public QoSCondition getQosCondition() {
        return qosCondition;
    }

    /**
     * Sets the value of the qosCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link QoSCondition }
     *     
     */
    public void setQosCondition(QoSCondition value) {
        this.qosCondition = value;
    }

    /**
     * Gets the value of the networkSlicingConditionParameters property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkSlicingConditionParameters }
     *     
     */
    public NetworkSlicingConditionParameters getNetworkSlicingConditionParameters() {
        return networkSlicingConditionParameters;
    }

    /**
     * Sets the value of the networkSlicingConditionParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkSlicingConditionParameters }
     *     
     */
    public void setNetworkSlicingConditionParameters(NetworkSlicingConditionParameters value) {
        this.networkSlicingConditionParameters = value;
    }

}
