//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.14 at 09:34:48 AM CET 
//


package eu.fluidos.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FirewallRuleAction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FirewallRuleAction"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}ConfigurationAction"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="firewallActionType" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}FirewallActionType" minOccurs="0"/&gt;
 *         &lt;element name="ruleParameters" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}FirewallConfigurationCondition" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FirewallRuleAction", propOrder = {
    "firewallActionType",
    "ruleParameters"
})
public class FirewallRuleAction
    extends ConfigurationAction
{

    @XmlSchemaType(name = "string")
    protected FirewallActionType firewallActionType;
    protected FirewallConfigurationCondition ruleParameters;

    /**
     * Gets the value of the firewallActionType property.
     * 
     * @return
     *     possible object is
     *     {@link FirewallActionType }
     *     
     */
    public FirewallActionType getFirewallActionType() {
        return firewallActionType;
    }

    /**
     * Sets the value of the firewallActionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FirewallActionType }
     *     
     */
    public void setFirewallActionType(FirewallActionType value) {
        this.firewallActionType = value;
    }

    /**
     * Gets the value of the ruleParameters property.
     * 
     * @return
     *     possible object is
     *     {@link FirewallConfigurationCondition }
     *     
     */
    public FirewallConfigurationCondition getRuleParameters() {
        return ruleParameters;
    }

    /**
     * Sets the value of the ruleParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link FirewallConfigurationCondition }
     *     
     */
    public void setRuleParameters(FirewallConfigurationCondition value) {
        this.ruleParameters = value;
    }

}
