//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.01 at 03:05:51 PM CEST 
//


package eu.fluidos.jaxb;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FiveGSecuritySliceAction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FiveGSecuritySliceAction"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}ConfigurationAction"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="fiveGSecuritySliceActionType" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}FiveGSecuritySliceActionType"/&gt;
 *         &lt;element name="securedService" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}SecuredService" maxOccurs="unbounded"/&gt;
 *         &lt;element name="nest" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}NEST" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FiveGSecuritySliceAction", propOrder = {
    "fiveGSecuritySliceActionType",
    "securedService",
    "nest"
})
public class FiveGSecuritySliceAction
    extends ConfigurationAction
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected FiveGSecuritySliceActionType fiveGSecuritySliceActionType;
    @XmlElement(required = true)
    protected List<SecuredService> securedService;
    protected NEST nest;

    /**
     * Gets the value of the fiveGSecuritySliceActionType property.
     * 
     * @return
     *     possible object is
     *     {@link FiveGSecuritySliceActionType }
     *     
     */
    public FiveGSecuritySliceActionType getFiveGSecuritySliceActionType() {
        return fiveGSecuritySliceActionType;
    }

    /**
     * Sets the value of the fiveGSecuritySliceActionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiveGSecuritySliceActionType }
     *     
     */
    public void setFiveGSecuritySliceActionType(FiveGSecuritySliceActionType value) {
        this.fiveGSecuritySliceActionType = value;
    }

    /**
     * Gets the value of the securedService property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the securedService property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSecuredService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SecuredService }
     * 
     * 
     */
    public List<SecuredService> getSecuredService() {
        if (securedService == null) {
            securedService = new ArrayList<SecuredService>();
        }
        return this.securedService;
    }

    /**
     * Gets the value of the nest property.
     * 
     * @return
     *     possible object is
     *     {@link NEST }
     *     
     */
    public NEST getNest() {
        return nest;
    }

    /**
     * Sets the value of the nest property.
     * 
     * @param value
     *     allowed object is
     *     {@link NEST }
     *     
     */
    public void setNest(NEST value) {
        this.nest = value;
    }

}
