//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.14 at 09:34:48 AM CET 
//


package eu.fluidos.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ICRA complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ICRA"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="ICRAchat" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="ICRAlanguagesexual" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="ICRAnuditygraphic" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="ICRAnuditytopless" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="ICRAnuditybottoms" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="ICRAdrugsuse" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="ICRAdrugsalcohol" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="ICRAviolencetofantasy" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ICRA")
public class ICRA {

    @XmlAttribute(name = "ICRAchat")
    protected Boolean icrAchat;
    @XmlAttribute(name = "ICRAlanguagesexual")
    protected Boolean icrAlanguagesexual;
    @XmlAttribute(name = "ICRAnuditygraphic")
    protected Boolean icrAnuditygraphic;
    @XmlAttribute(name = "ICRAnuditytopless")
    protected Boolean icrAnuditytopless;
    @XmlAttribute(name = "ICRAnuditybottoms")
    protected Boolean icrAnuditybottoms;
    @XmlAttribute(name = "ICRAdrugsuse")
    protected Boolean icrAdrugsuse;
    @XmlAttribute(name = "ICRAdrugsalcohol")
    protected Boolean icrAdrugsalcohol;
    @XmlAttribute(name = "ICRAviolencetofantasy")
    protected Boolean icrAviolencetofantasy;

    /**
     * Gets the value of the icrAchat property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isICRAchat() {
        return icrAchat;
    }

    /**
     * Sets the value of the icrAchat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setICRAchat(Boolean value) {
        this.icrAchat = value;
    }

    /**
     * Gets the value of the icrAlanguagesexual property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isICRAlanguagesexual() {
        return icrAlanguagesexual;
    }

    /**
     * Sets the value of the icrAlanguagesexual property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setICRAlanguagesexual(Boolean value) {
        this.icrAlanguagesexual = value;
    }

    /**
     * Gets the value of the icrAnuditygraphic property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isICRAnuditygraphic() {
        return icrAnuditygraphic;
    }

    /**
     * Sets the value of the icrAnuditygraphic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setICRAnuditygraphic(Boolean value) {
        this.icrAnuditygraphic = value;
    }

    /**
     * Gets the value of the icrAnuditytopless property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isICRAnuditytopless() {
        return icrAnuditytopless;
    }

    /**
     * Sets the value of the icrAnuditytopless property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setICRAnuditytopless(Boolean value) {
        this.icrAnuditytopless = value;
    }

    /**
     * Gets the value of the icrAnuditybottoms property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isICRAnuditybottoms() {
        return icrAnuditybottoms;
    }

    /**
     * Sets the value of the icrAnuditybottoms property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setICRAnuditybottoms(Boolean value) {
        this.icrAnuditybottoms = value;
    }

    /**
     * Gets the value of the icrAdrugsuse property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isICRAdrugsuse() {
        return icrAdrugsuse;
    }

    /**
     * Sets the value of the icrAdrugsuse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setICRAdrugsuse(Boolean value) {
        this.icrAdrugsuse = value;
    }

    /**
     * Gets the value of the icrAdrugsalcohol property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isICRAdrugsalcohol() {
        return icrAdrugsalcohol;
    }

    /**
     * Sets the value of the icrAdrugsalcohol property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setICRAdrugsalcohol(Boolean value) {
        this.icrAdrugsalcohol = value;
    }

    /**
     * Gets the value of the icrAviolencetofantasy property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isICRAviolencetofantasy() {
        return icrAviolencetofantasy;
    }

    /**
     * Sets the value of the icrAviolencetofantasy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setICRAviolencetofantasy(Boolean value) {
        this.icrAviolencetofantasy = value;
    }

}
