//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.01 at 03:05:51 PM CEST 
//


package eu.fluidos.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KubernetesNetworkFilteringAction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KubernetesNetworkFilteringAction"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}ConfigurationAction"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="KubernetesNetworkFilteringActionType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KubernetesNetworkFilteringAction", propOrder = {
    "kubernetesNetworkFilteringActionType"
})
public class KubernetesNetworkFilteringAction
    extends ConfigurationAction
{

    @XmlElement(name = "KubernetesNetworkFilteringActionType", required = true)
    protected String kubernetesNetworkFilteringActionType;

    /**
     * Gets the value of the kubernetesNetworkFilteringActionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKubernetesNetworkFilteringActionType() {
        return kubernetesNetworkFilteringActionType;
    }

    /**
     * Sets the value of the kubernetesNetworkFilteringActionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKubernetesNetworkFilteringActionType(String value) {
        this.kubernetesNetworkFilteringActionType = value;
    }

}
