//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.01 at 03:05:51 PM CEST 
//


package eu.fluidos.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LearningParameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LearningParameters"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}ConfigurationCondition"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="testSize" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="localEpochs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="batchSize" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="stepsPerEpoch" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LearningParameters", propOrder = {
    "testSize",
    "localEpochs",
    "batchSize",
    "stepsPerEpoch"
})
public class LearningParameters
    extends ConfigurationCondition
{

    protected String testSize;
    protected String localEpochs;
    protected String batchSize;
    protected String stepsPerEpoch;

    /**
     * Gets the value of the testSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestSize() {
        return testSize;
    }

    /**
     * Sets the value of the testSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestSize(String value) {
        this.testSize = value;
    }

    /**
     * Gets the value of the localEpochs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalEpochs() {
        return localEpochs;
    }

    /**
     * Sets the value of the localEpochs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalEpochs(String value) {
        this.localEpochs = value;
    }

    /**
     * Gets the value of the batchSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchSize() {
        return batchSize;
    }

    /**
     * Sets the value of the batchSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchSize(String value) {
        this.batchSize = value;
    }

    /**
     * Gets the value of the stepsPerEpoch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStepsPerEpoch() {
        return stepsPerEpoch;
    }

    /**
     * Sets the value of the stepsPerEpoch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStepsPerEpoch(String value) {
        this.stepsPerEpoch = value;
    }

}
