//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.14 at 09:34:48 AM CET 
//


package eu.fluidos.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MonitoringActionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="MonitoringActionType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ALERT"/&gt;
 *     &lt;enumeration value="SECURITY_ANALYSIS"/&gt;
 *     &lt;enumeration value="ENABLE_SESS_STATS"/&gt;
 *     &lt;enumeration value="ENABLE_NO_SESS_STATS"/&gt;
 *     &lt;enumeration value="BEHAVIORAL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "MonitoringActionType")
@XmlEnum
public enum MonitoringActionType {

    ALERT,
    SECURITY_ANALYSIS,
    ENABLE_SESS_STATS,
    ENABLE_NO_SESS_STATS,
    BEHAVIORAL;

    public String value() {
        return name();
    }

    public static MonitoringActionType fromValue(String v) {
        return valueOf(v);
    }

}
