//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.14 at 09:34:48 AM CET 
//


package eu.fluidos.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NetworkSlicingConfigurationCondition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NetworkSlicingConfigurationCondition"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}NetworkSlicingCondition"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="networkSlicingCondition" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}NetworkSlicingCondition" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NetworkSlicingConfigurationCondition", propOrder = {
    "networkSlicingCondition"
})
public class NetworkSlicingConfigurationCondition
    extends NetworkSlicingCondition
{

    protected NetworkSlicingCondition networkSlicingCondition;

    /**
     * Gets the value of the networkSlicingCondition property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkSlicingCondition }
     *     
     */
    public NetworkSlicingCondition getNetworkSlicingCondition() {
        return networkSlicingCondition;
    }

    /**
     * Sets the value of the networkSlicingCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkSlicingCondition }
     *     
     */
    public void setNetworkSlicingCondition(NetworkSlicingCondition value) {
        this.networkSlicingCondition = value;
    }

}
