//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.14 at 09:34:48 AM CET 
//


package eu.fluidos.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NetworkSlicingAction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NetworkSlicingAction"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}ConfigurationAction"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="NetworkSlicingActionType" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}NetworkSlicingActionType" minOccurs="0"/&gt;
 *         &lt;element name="networkSlicingConditionParameters" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}NetworkSlicingConfigurationCondition" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NetworkSlicingAction", propOrder = {
    "networkSlicingActionType",
    "networkSlicingConditionParameters"
})
public class NetworkSlicingAction
    extends ConfigurationAction
{

    @XmlElement(name = "NetworkSlicingActionType")
    @XmlSchemaType(name = "string")
    protected NetworkSlicingActionType networkSlicingActionType;
    protected NetworkSlicingConfigurationCondition networkSlicingConditionParameters;

    /**
     * Gets the value of the networkSlicingActionType property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkSlicingActionType }
     *     
     */
    public NetworkSlicingActionType getNetworkSlicingActionType() {
        return networkSlicingActionType;
    }

    /**
     * Sets the value of the networkSlicingActionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkSlicingActionType }
     *     
     */
    public void setNetworkSlicingActionType(NetworkSlicingActionType value) {
        this.networkSlicingActionType = value;
    }

    /**
     * Gets the value of the networkSlicingConditionParameters property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkSlicingConfigurationCondition }
     *     
     */
    public NetworkSlicingConfigurationCondition getNetworkSlicingConditionParameters() {
        return networkSlicingConditionParameters;
    }

    /**
     * Sets the value of the networkSlicingConditionParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkSlicingConfigurationCondition }
     *     
     */
    public void setNetworkSlicingConditionParameters(NetworkSlicingConfigurationCondition value) {
        this.networkSlicingConditionParameters = value;
    }

}
