//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.01 at 03:05:51 PM CEST 
//


package eu.fluidos.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PowerMgmtAction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PowerMgmtAction"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}ConfigurationAction"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PowerMgmtActionType" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}PowerMgmtActionType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PowerMgmtAction", propOrder = {
    "powerMgmtActionType"
})
public class PowerMgmtAction
    extends ConfigurationAction
{

    @XmlElement(name = "PowerMgmtActionType", required = true)
    @XmlSchemaType(name = "string")
    protected PowerMgmtActionType powerMgmtActionType;

    /**
     * Gets the value of the powerMgmtActionType property.
     * 
     * @return
     *     possible object is
     *     {@link PowerMgmtActionType }
     *     
     */
    public PowerMgmtActionType getPowerMgmtActionType() {
        return powerMgmtActionType;
    }

    /**
     * Sets the value of the powerMgmtActionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PowerMgmtActionType }
     *     
     */
    public void setPowerMgmtActionType(PowerMgmtActionType value) {
        this.powerMgmtActionType = value;
    }

}
