//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.14 at 09:34:48 AM CET 
//


package eu.fluidos.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrivacyAction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PrivacyAction"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}ConfigurationAction"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PrivacyActionType" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}PrivacyActionType"/&gt;
 *         &lt;element name="PrivacyMethod" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}PrivacyMethod"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrivacyAction", propOrder = {
    "privacyActionType",
    "privacyMethod"
})
public class PrivacyAction
    extends ConfigurationAction
{

    @XmlElement(name = "PrivacyActionType", required = true)
    @XmlSchemaType(name = "string")
    protected PrivacyActionType privacyActionType;
    @XmlElement(name = "PrivacyMethod", required = true)
    protected PrivacyMethod privacyMethod;

    /**
     * Gets the value of the privacyActionType property.
     * 
     * @return
     *     possible object is
     *     {@link PrivacyActionType }
     *     
     */
    public PrivacyActionType getPrivacyActionType() {
        return privacyActionType;
    }

    /**
     * Sets the value of the privacyActionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrivacyActionType }
     *     
     */
    public void setPrivacyActionType(PrivacyActionType value) {
        this.privacyActionType = value;
    }

    /**
     * Gets the value of the privacyMethod property.
     * 
     * @return
     *     possible object is
     *     {@link PrivacyMethod }
     *     
     */
    public PrivacyMethod getPrivacyMethod() {
        return privacyMethod;
    }

    /**
     * Sets the value of the privacyMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrivacyMethod }
     *     
     */
    public void setPrivacyMethod(PrivacyMethod value) {
        this.privacyMethod = value;
    }

}
