//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.14 at 09:34:48 AM CET 
//


package eu.fluidos.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrafficAnalysisCapability complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrafficAnalysisCapability"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}Capability"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="supportOnlineTraficAnalysis" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="supportOfflineTraficAnalysis" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrafficAnalysisCapability", propOrder = {
    "supportOnlineTraficAnalysis",
    "supportOfflineTraficAnalysis"
})
@XmlSeeAlso({
    IDSCapability.class,
    IPSCapability.class,
    MalwaresAnalysisCapability.class,
    LawfulInterceptionCapability.class
})
public class TrafficAnalysisCapability
    extends Capability
{

    protected boolean supportOnlineTraficAnalysis;
    protected boolean supportOfflineTraficAnalysis;

    /**
     * Gets the value of the supportOnlineTraficAnalysis property.
     * 
     */
    public boolean isSupportOnlineTraficAnalysis() {
        return supportOnlineTraficAnalysis;
    }

    /**
     * Sets the value of the supportOnlineTraficAnalysis property.
     * 
     */
    public void setSupportOnlineTraficAnalysis(boolean value) {
        this.supportOnlineTraficAnalysis = value;
    }

    /**
     * Gets the value of the supportOfflineTraficAnalysis property.
     * 
     */
    public boolean isSupportOfflineTraficAnalysis() {
        return supportOfflineTraficAnalysis;
    }

    /**
     * Sets the value of the supportOfflineTraficAnalysis property.
     * 
     */
    public void setSupportOfflineTraficAnalysis(boolean value) {
        this.supportOfflineTraficAnalysis = value;
    }

}
