apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "network-policies-cluster-role"
  namespace: fluidos
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["create", "get", "list", "delete"]
